{{- if .Values.apiserver.configuration.additionalConfigs -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "clearml.fullname" . }}-apiserver-configmap"
  labels:
    {{- include "clearml.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.apiserver.configuration.additionalConfigs }}
  {{ $key }}: |
    {{- $val | nindent 4 }}
  {{- end }}
{{- end -}}
