{{- if .Values.agentk8sglue.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "clearml.fullname" . }}-k8sagent"
  labels:
    app: k8sagent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8sagent
  template:
    metadata:
      labels:
        app: k8sagent
    spec:
      containers:
      - name: k8s-glue-container
        image: "{{ .Values.agentk8sglue.image.repository }}:{{ .Values.agentk8sglue.image.tag }}"
        imagePullPolicy: Always
        command: ["/bin/bash", "-c", "export PATH=$PATH:$HOME/bin; source /root/.bashrc && /root/entrypoint.sh"]
        volumeMounts:
          - name: k8sagent-pod-template
            mountPath: /root/template
        env:
          - name: CLEARML_API_HOST
            value: "http://{{ include "clearml.fullname" . }}-apiserver:{{ .Values.apiserver.service.port }}"
          - name: CLEARML_WEB_HOST
            value: "http://{{ include "clearml.fullname" . }}-webserver"
          - name: CLEARML_FILES_HOST
            value: "http://{{ include "clearml.fullname" . }}-fileserver:{{ .Values.fileserver.service.port }}"
          - name: K8S_GLUE_MAX_PODS
            value: "{{.Values.agentk8sglue.maxPods}}"
          - name: K8S_GLUE_QUEUE
            value: "{{.Values.agentk8sglue.queue}}"
          - name: K8S_GLUE_EXTRA_ARGS
            value: "--namespace {{ .Release.Namespace }} --template-yaml /root/template/template.yaml"
          - name: K8S_DEFAULT_NAMESPACE
            value: "{{ .Release.Namespace }}"
          - name: CLEARML_API_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: clearml-conf
                key: apiserver_key
          - name: CLEARML_API_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: clearml-conf
                key: apiserver_secret
          - name: CLEARML_WORKER_ID
            value: "{{.Values.agentk8sglue.id}}"
          - name: CLEARML_AGENT_UPDATE_REPO
            value: ""
          - name: FORCE_CLEARML_AGENT_REPO
            value: ""
          - name: CLEARML_DOCKER_IMAGE
            value: "{{.Values.agentk8sglue.defaultDockerImage}}"
      volumes:
        - name: k8sagent-pod-template
          configMap: 
            name: k8sagent-pod-template
{{- end }}

