{{- if .Values.ingress.enabled -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "clearml.fullname" . }}-app
  labels:
    {{- include "clearml.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls.secretName }}
  tls:
    - hosts:
        - "{{ .Values.ingress.hostPrefixApp }}.{{ .Values.ingress.host }}"
      secretName: "{{ .Values.ingress.name }}-{{ .Values.ingress.hostPrefixApi }}"
  {{- end }}
  rules:
    - host: "{{ .Values.ingress.hostPrefixApp }}.{{ .Values.ingress.host }}"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              serviceName: {{ include "clearml.fullname" . }}-webserver
              servicePort: {{ .Values.webserver.service.port }}
{{- end }}
