{{- if .Values.ingress.enabled -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "clearml.fullname" . }}-api
  labels:
    {{- include "clearml.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.api.tlsSecretName }}
  tls:
    - hosts:
        - {{ .Values.ingress.api.hostName }}
      secretName: {{ .Values.ingress.api.tlsSecretName }}
  {{- end }}
  rules:
  - host: {{ .Values.ingress.api.hostName }}
    http:
      paths:
      - path: "/"
  {{ if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
        pathType: Prefix
        backend:
          service:
            name: {{ include "clearml.fullname" . }}-apiserver
            port:
              number: {{ .Values.apiserver.service.port }}
  {{ else }}
        backend:
          serviceName: {{ include "clearml.fullname" . }}-apiserver
          servicePort: {{ .Values.apiserver.service.port }}
  {{ end }}
{{- end }}
