{{- if .Values.ingress.enabled -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "clearml.fullname" . }}-files
  labels:
    {{- include "clearml.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - "{{ .Values.ingress.hostPrefixFiles }}.{{ .Values.ingress.host }}"
      {{- if not .Values.ingress.tls.secretName }}
      secretName: "{{ .Values.ingress.name }}-{{ .Values.ingress.hostPrefixFiles }}"
      {{- else }}
      secretName: "{{ .Values.ingress.tls.secretName }}"
      {{- end }}
  {{- end }}
  rules:
    - host: "{{ .Values.ingress.hostPrefixFiles }}.{{ .Values.ingress.host }}"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              serviceName: {{ include "clearml.fullname" . }}-fileserver
              servicePort: {{ .Values.fileserver.service.port }}
{{- end }}
