{{- if .Values.ingress.files.enabled -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "clearml.fullname" . }}-files
  labels:
    {{- include "clearml.labels" . | nindent 4 }}
  {{- $annotations := .Values.ingress.annotations }}
  {{- if .Values.ingress.files.annotations }}
  {{- $annotations = mergeOverwrite $annotations .Values.ingress.files.annotations }}
  {{- end }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}
spec:
  {{- if .Values.ingress.files.tlsSecretName }}
  tls:
    - hosts:
        - {{ .Values.ingress.files.hostName }}
      secretName: {{ .Values.ingress.files.tlsSecretName }}
  {{- end }}
  rules:
  - host: {{ .Values.ingress.files.hostName }}
    http:
      paths:
      - path: {{ .Values.ingress.files.path }}
  {{ if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
        pathType: Prefix
        backend:
          service:
            name: {{ include "clearml.fullname" . }}-fileserver
            port:
              number: {{ .Values.fileserver.service.port }}
  {{ else }}
        backend:
          serviceName: {{ include "clearml.fullname" . }}-fileserver
          servicePort: {{ .Values.fileserver.service.port }}
  {{ end }}
{{- end }}
