{{- if .Values.agentk8sglue.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8sagent-pods-access
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs: ["get", "list", "watch", "create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8sagent-pods-access
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Release.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k8sagent-pods-access
{{- end }}
