{{- if not .Values.secret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: clearml-conf
stringData:
  apiserver_key: {{ .Values.secret.credentials.apiserver.accessKey }}
  apiserver_secret: {{ .Values.secret.credentials.apiserver.secretKey }}
  http_session: {{ .Values.secret.httpSession }}
  auth_token: {{ .Values.secret.authToken }}
  tests_user_key: {{ .Values.secret.credentials.tests.accessKey }}
  tests_user_secret: {{ .Values.secret.credentials.tests.secretKey }}
{{- end }}
