apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.apiserver.serviceAccountName }}-apiserver
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.fileserver.serviceAccountName }}-fileserver
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.webserver.serviceAccountName }}-webserver
