apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.apiserver.serviceAccountName }}-apiserver
  {{- if .Values.apiserver.serviceAccountAnnotations }}
  annotations:
    {{- toYaml .Values.apiserver.serviceAccountAnnotations | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.fileserver.serviceAccountName }}-fileserver
  {{- if .Values.fileserver.serviceAccountAnnotations }}
  annotations:
    {{- toYaml .Values.fileserver.serviceAccountAnnotations | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.webserver.serviceAccountName }}-webserver
  {{- if .Values.webserver.serviceAccountAnnotations }}
  annotations:
    {{- toYaml .Values.webserver.serviceAccountAnnotations | nindent 4 }}
  {{- end }}
