{{- if .Values.webserver.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "webserver.referenceName" . }}-configmap"
  labels:
    {{- include "clearml.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.webserver.additionalConfigs }}
  {{ $key }}: |
    {{- $val | nindent 4 }}
  {{- end }}
{{- end -}}
