{{- if .Values.webserver.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "webserver.referenceName" . }}
  labels:
    {{- include "clearml.labels" . | nindent 4 }}
  {{- with .Values.webserver.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.webserver.service.type }}
  ports:
    - port: {{ .Values.webserver.service.port }}
      {{- if .Values.enterpriseFeatures.enabled }}
      targetPort: 8080
      {{- else }}
      targetPort: 80
      {{- end }}
      {{- if eq .Values.webserver.service.type "NodePort" }}
      nodePort: {{ .Values.webserver.service.nodePort }}
      {{- end }}
      protocol: TCP
  selector:
    {{- include "webserver.selectorLabels" . | nindent 4 }}
{{- end }}
