apiserver:
  service:
    type: ClusterIP
  ingress:
    enabled: true
    hostName: "api.clearml.127-0-0-1.nip.io"
fileserver:
  service:
    type: ClusterIP
  ingress:
    enabled: true
    hostName: "files.clearml.127-0-0-1.nip.io"
webserver:
  service:
    type: ClusterIP
  ingress:
    enabled: true
    hostName: "app.clearml.127-0-0-1.nip.io"
redis:
  architecture: replication
  master:
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 5Gi
      ## If undefined (the default) or set to null, no storageClassName spec is set, choosing the default provisioner
      storageClass: null
  replica:
    replicaCount: 2
mongodb:
  enabled: true
  architecture: replicaset
  replicaCount: 2
  arbiter:
    enabled: false
  pdb:
    create: true
  podAntiAffinityPreset: soft
elasticsearch:
  replicas: 3
