apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    clearml.serving.service: alertmanager
  name: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      clearml.serving.service: alertmanager
  strategy: {}
  template:
    metadata:
      annotations: {}
      labels:
        clearml.serving.network/clearml-serving-backend: "true"
        clearml.serving.service: alertmanager
    spec:
      containers:
        - image: {{ .Values.alertmanager.image }}
          name: clearml-serving-alertmanager
          ports:
            - containerPort: 9093
          resources: {}
      restartPolicy: Always
status: {}
