{{ if .Values.clearml_serving_triton.enabled }}
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    clearml.serving.service: {{ include "clearml-serving.fullname" . }}-triton
  name: {{ include "clearml-serving.fullname" . }}-triton
spec:
  ports:
    - name: "8001"
      port: 8001
      targetPort: 8001
  selector:
    clearml.serving.service: {{ include "clearml-serving.fullname" . }}-triton
{{ end }}
