{{- if .Values.clearml_serving_inference.additionalConfigs }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "clearmlServing.fullname" . }}-inference-configmap"
  labels:
    {{- include "clearmlServing.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.clearml_serving_inference.additionalConfigs }}
  {{ $key }}: |
    {{- $val | nindent 4 }}
  {{- end }}
{{- end }}
