{{- if .Values.clearml_serving_triton.enabled }}
{{- if .Values.clearml_serving_triton.additionalConfigs }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "clearmlServing.fullname" . }}-triton-configmap"
  labels:
    {{- include "clearmlServing.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.clearml_serving_triton.additionalConfigs }}
  {{ $key }}: |
    {{- $val | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
