apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: clearml-serving-backend
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              clearml.serving.network/clearml-serving-backend: "true"
  podSelector:
    matchLabels:
      clearml.serving.network/clearml-serving-backend: "true"
