apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    clearml.serving.service: kafka
  name: clearml-serving-kafka
spec:
  ports:
    - name: "9092"
      port: 9092
      targetPort: 9092
  selector:
    clearml.serving.service: kafka
status:
  loadBalancer: {}
