apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    clearml.serving.service: prometheus
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      clearml.serving.service: prometheus
  strategy:
    type: Recreate
  template:
    metadata:
      annotations: {}
      labels:
        clearml.serving.network/clearml-serving-backend: "true"
        clearml.serving.service: prometheus
    spec:
      containers:
        - args:
            - --config.file=/mnt/prometheus.yml
            - --storage.tsdb.path=/prometheus
            - --web.console.libraries=/etc/prometheus/console_libraries
            - --web.console.templates=/etc/prometheus/consoles
            - --storage.tsdb.retention.time=200h
            - --web.enable-lifecycle
          image: {{ .Values.prometheus.image }}
          name: clearml-serving-prometheus
          ports:
            - containerPort: 9090
          resources: {}
          volumeMounts:
            - mountPath: /mnt
              name: prometheus-conf
      restartPolicy: Always
      volumes:
        - name: prometheus-conf
          secret:
            secretName: prometheus-config
status: {}
