apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agentk8sglue.referenceName" . }}-k8sagent-pod-template
data:
  template.yaml: |
    apiVersion: v1
    metadata:
      namespace: {{ .Release.Namespace }}
    spec:
      {{- if .Values.imageCredentials.enabled }}
      imagePullSecrets:
      {{- if .Values.imageCredentials.existingSecret }}
      - name: .Values.imageCredentials.existingSecret
      {{- else }}
      - name: {{ include "agentk8sglue.referenceName" . }}-clearml-agent-registry-key
      {{- end }}
      {{- end }}
      serviceAccountName: {{ .Values.agentk8sglue.serviceAccountName }}
      volumes:
      {{- range .Values.agentk8sglue.podTemplate.volumes }}
      - name: {{ .name }}
        persistentVolumeClaim:
          claimName: {{ .name }}
      {{- end }}
      containers:
      - resources:
          {{- toYaml .Values.agentk8sglue.podTemplate.resources | nindent 10 }}
        ports:
        - containerPort: 10022
        volumeMounts:
        {{- range .Values.agentk8sglue.podTemplate.volumes }}
        - mountPath: {{ .path }}
          name: {{ .name }}
        {{- end }}
        env:
        - name: CLEARML_API_HOST
          value: {{.Values.agentk8sglue.apiServerUrlReference}}
        - name: CLEARML_WEB_HOST
          value: {{.Values.agentk8sglue.webServerUrlReference}}
        - name: CLEARML_FILES_HOST
          value: {{.Values.agentk8sglue.fileServerUrlReference}}
        - name: CLEARML_API_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "agentk8sglue.referenceName" . }}-clearml-agent-conf
              key: agentk8sglue_key
        - name: CLEARML_API_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "agentk8sglue.referenceName" . }}-clearml-agent-conf
              key: agentk8sglue_secret
        {{- if .Values.agentk8sglue.podTemplate.env }}
        {{ toYaml .Values.agentk8sglue.podTemplate.env | nindent 8 }}
        {{- end }}
        {{- with .Values.agentk8sglue.podTemplate.nodeSelector}}
      nodeSelector:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.agentk8sglue.podTemplate.tolerations }}
      tolerations:
          {{- toYaml . | nindent 8 }}
        {{- end }}
