{{ if .Values.agentk8sglue.fileMounts }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clearml.name" . }}-afm
data:
  {{- range .Values.agentk8sglue.fileMounts }}
  {{ .name }}: {{ .fileContent | b64enc }}
  {{- end }}
{{ end }}
---
{{- if .Values.enterpriseFeatures.enabled }}
{{ if .Values.agentk8sglue.basePodTemplate.fileMounts }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clearml.name" . }}-fm
data:
  {{- range .Values.agentk8sglue.basePodTemplate.fileMounts }}
  {{ .name }}: {{ .fileContent | b64enc }}
  {{- end }}
{{ end }}
---
{{- range $key, $value := $.Values.agentk8sglue.queues }}
{{ if .templateOverrides.fileMounts }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clearml.name" $ }}-{{ $key }}-fm
data:
  {{- range .templateOverrides.fileMounts }}
  {{ .name }}: {{ .fileContent | b64enc }}
  {{- end }}
{{ end }}
---
{{- end }}
{{- end }}
