{{ if .Values.agentk8sglue.fileMounts }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clearmlAgent.fullname" . }}-afm
data:
  {{- range .Values.agentk8sglue.fileMounts }}
  {{ .name }}: {{ .fileContent | b64enc }}
  {{- end }}
{{ end }}
