name: Lint and Test Charts

on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
    paths:
      - 'charts/**'

jobs:
  lint-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Run helm-docs
        run: .github/helm-docs.sh
  install-chart:
    name: install-chart
    runs-on: ubuntu-latest
    needs:
      - lint-docs
    strategy:
      matrix:
        k8s:
          - v1.27.11
          - v1.28.7
          - v1.29.2
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Create kind ${{ matrix.k8s }} cluster
        uses: helm/kind-action@v1.8.0
        with:
          node_image: kindest/node:${{ matrix.k8s }}
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.5.0
        with:
          version: v3.8.0
      - name: Add bitnami repo
        run: helm repo add bitnami https://charts.bitnami.com/bitnami
      - name: Add elastic repo
        run: helm repo add elastic https://helm.elastic.co
      - name: Add prometheus repo
        run: helm repo add prometheus https://prometheus-community.github.io/helm-charts
      - name: Add grafana repo
        run: helm repo add grafana https://grafana.github.io/helm-charts
      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --chart-dirs charts --target-branch main)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
            echo "changed_charts=\"${changed//$'\n'/,}\"" >> "$GITHUB_OUTPUT"
          fi
      - name: Inject secrets
        run: |
          find ./charts/*/ci/*.yaml -type f -exec sed -i "s/AGENTK8SGLUEKEY/${{ secrets.AGENTK8SGLUEKEY }}/g" {} \;
          find ./charts/*/ci/*.yaml -type f -exec sed -i "s/AGENTK8SGLUESECRET/${{ secrets.AGENTK8SGLUESECRET }}/g" {} \;
        if: steps.list-changed.outputs.changed == 'true'
      - name: Run chart-testing (lint and install)
        run: ct lint-and-install --chart-dirs charts --target-branch main --helm-extra-args "--timeout=15m" --charts=${{steps.list-changed.outputs.changed_charts}} --debug true
        if: steps.list-changed.outputs.changed == 'true'
