name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Add bitnami repo
        run: helm repo add bitnami https://charts.bitnami.com/bitnami
      - name: Add elastic repo
        run: helm repo add elastic https://helm.elastic.co
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: '${{ secrets.CR_TOKEN }}'
        with:
          charts_dir: charts
